
(define (newton-transform g)
	(lambda (x) (- x (/ (g x) ((deriv g) x))))
)
(define (newtons-method g guess)
	(fixed-point (newton-transform g) guess)
)

(define tolerance 0.00001)
(define (fixed-point f first-guess)
	(define (close-point v1 v2)
		(< (abs (- v1 v2)) tolerance)
	)
	(define (try guess number)
		(let ((next (f guess)))
		(display "Guess number ")
		(display number)
		(display " :  ")
		(display next)
		(newline)
			(if (close-enough? guess next)
				next
				(try next (+ number 1))
			))
	)
	(try first-guess 1)
)
