
(define (length items)
	(define (length-iter a count)
		(if (null? a)
			count
			(length-iter (cdr a) (+ 1 count))
		)
	)
	(length-iter items 0)
)
(define (list-ref items n)
	(if (= n 0)
		(car items)
		(list-ref (cdr items) (- n 1))
	)
)
(define (last-pair items)
	(let ((l (length items)))
		  (list-ref items (- l 1)))
)

(display (last-pair (list 23 72 149 34)))
